#
#Tue May 26 15:44:16 BST 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[--remote-allow-origins\=*,--disable-web-security,--disable-features\=VizDisplayCompositor,--start-maximized], extensions\=[]}
